services:
  api:
    build: 
      context: api
      target: debugger
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - redis
    environment:
      - PYDEVD_DISABLE_FILE_VALIDATION=1

  redis:
    image: redis:7
    ports:
      - "6379:6379"