apiVersion: apps/v1
kind: Deployment
metadata:
  name: click-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: click-app
  template:
    metadata:
      labels:
        app: click-app
    spec:
      containers:
        - name: click-app
          image: click-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: "redis"